import SlotsProvider from '@/providers/SlotsProvider'
import AppointmentsProvider from '@/providers/AppointmentsProvider'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import CandidatesProvider from '@/providers/CandidatesProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RhSystem',
  //description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='layout'>
          <SlotsProvider>
            <AppointmentsProvider>
              <CandidatesProvider>
                {children}
              </CandidatesProvider>
            </AppointmentsProvider>
          </SlotsProvider>
        </div>
      </body>
    </html>
  )
}
