export { fetchAllSlotsService } from './fetchAllSlots'
export { FetchCepService } from './fetchCepService'
export { GetAvaiableSlotService } from './getAvaiableSlots'
export { ConfirmAppointmentService } from './confirmAppointment'
export { SendNewAppointment } from './sendAppointment'
export { GenerateAccessKeyService } from './generateAccessKey'
export { ValidateAccessKeyService } from './validateAccessKeyService'